# Generated by Django 5.0 on 2025-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'PIX'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('transferencia', 'Transferência Bancária'), ('boleto', 'Boleto'), ('outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.CharField(choices=[('ordem_servico', 'Ordem de Serviço'), ('outros', 'Outros'), ('materiais', 'Materiais'), ('salarios', 'Salários'), ('aluguel', 'Aluguel'), ('agua_luz', 'Água/Luz'), ('equipamentos', 'Equipamentos'), ('outros', 'Outros')], max_length=20),
        ),
    ]
