# Generated by Django 5.1.7 on 2025-04-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('valor_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tempo_estimado_producao', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Bolso',
                'verbose_name_plural': 'Tipos de Bolsos',
                'ordering': ['nome'],
            },
        ),
    ]
