# Generated by Django 5.0 on 2025-05-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobolso',
            name='custo_producao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor a ser pago ao funcionário por unidade produzida', max_digits=10),
        ),
    ]
