# Generated by Django 5.1.7 on 2025-04-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaoos',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
