# Generated by Django 5.0 on 2025-05-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_alter_producaoos_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordemservico',
            name='cor_linha',
            field=models.CharField(blank=True, help_text='Cor da linha utilizada', max_length=100),
        ),
        migrations.AddField(
            model_name='itemordemservico',
            name='custo_producao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Custo de produção por unidade', max_digits=10),
        ),
    ]
